name: Onceler Deploy

on:
  push:
    branches: [master]
  schedule:
    - cron: '30 9 * * 0' # Every Sunday at 9:30AM UTC (5:30AM EST)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby installation
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false

      - name: Deploy to cloud.gov
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_api: ${{ secrets.CF_API }}
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}
